"""Generate the app's quote data from the Excel workbook.

Run from the project root:
    python3 scripts/generate_data.py

The script reads the workbook row by row (including cached formula values),
keeps the original currency and amount, and writes src/generatedQuoteData.ts.
"""
from __future__ import annotations

import html
import json
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "Europa2027_Cotizacion_plan_completo (1).xlsx"
OUTPUT = ROOT / "src" / "generatedQuoteData.ts"
NS = {"x": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}


def shared_strings(book: zipfile.ZipFile) -> list[str]:
    root = ET.fromstring(book.read("xl/sharedStrings.xml"))
    return ["".join(node.text or "" for node in item.iter() if node.tag.endswith("}t")) for item in root.findall("x:si", NS)]


def value(cell: ET.Element, strings: list[str]) -> str:
    node = cell.find("x:v", NS)
    raw = "" if node is None else node.text or ""
    if cell.attrib.get("t") == "s" and raw:
        return strings[int(raw)]
    return raw


def number(text: str) -> float | None:
    try:
        return float(text)
    except (TypeError, ValueError):
        return None


def read_rows(sheet_number: int, option_name: str) -> list[dict[str, object]]:
    with zipfile.ZipFile(WORKBOOK) as book:
        strings = shared_strings(book)
        sheet = ET.fromstring(book.read(f"xl/worksheets/sheet{sheet_number}.xml"))
        rows: list[dict[str, object]] = []
        headers: list[str] = []
        for row in sheet.findall(".//x:sheetData/x:row", NS):
            cells = {cell.attrib["r"]: value(cell, strings) for cell in row.findall("x:c", NS)}
            values = [cells.get(f"{column}{row.attrib['r']}", "") for column in "ABCDEFGHIJKLM"]
            if values[0] == "Categoría" and values[4] == "Moneda":
                headers = values
                continue
            if not headers or values[0] not in {"Vuelos y Trenes", "Traslados", "Alojamiento", "Crucero", "Tours y Excursiones", "Comidas", "Seguro de Viaje", "Otros y Extras"}:
                continue
            rows.append({
                "option": option_name, "category": values[0], "place": values[1], "date": values[2],
                "title": values[3], "currency": values[4] or "COP",
                "unitOriginal": number(values[5]), "quantity": number(values[6]),
                "totalOriginal": number(values[7]), "rateToCop": number(values[8]),
                "totalCop": number(values[9]), "perPersonCop": number(values[10]),
                "note": html.unescape(values[11]),
            })
        return rows


def ts(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    sheets = [(4, "Completo"), (6, "Zúrich y Crucero"), (8, "Múnich y Crucero"), (10, "Solo crucero")]
    rows = [line for sheet, name in sheets for line in read_rows(sheet, name)]
    OUTPUT.write_text(
        "// Generated by scripts/generate_data.py — do not edit manually.\n"
        "export type ExcelQuoteLine = { option: string; category: string; place: string; date: string; title: string; currency: string; unitOriginal: number | null; quantity: number | null; totalOriginal: number | null; rateToCop: number | null; totalCop: number | null; perPersonCop: number | null; note: string };\n"
        f"export const excelQuoteLines: ExcelQuoteLine[] = {ts(rows)};\n",
        encoding="utf-8",
    )
    print(f"Generated {len(rows)} quote lines at {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
